### ISSUE TITLE
Drop "ON" from title

### ISSUE THREAD

**Issue by jeffpc** [illumos/dev-guide#11]
Throughout the guide, the guide is called "Illumos developer's guide" however the page titles call it "illumos ON Developer's Guide".  This is inconsistent at the very least, and mildly confusing at worst - illumos is what used to be ON.  There's no Illumos ON.

**Comment by rzezeski** [comment]
FWIW, as a beginner the acronym ON escaped me. I saw it mentioned a lot but never a definition of what it stood for. From what I can tell, having ON in the title doesn't convey any additional information, so I'm +1 to removing it.

**Comment by rmustacc** [comment]
Resolved in c7e18cdfe570c1b79e20f09f949b1c96f6bf7338.
