### ISSUE TITLE
markdown2.py version doesn't handle contiguous ``` blocks

### ISSUE THREAD

**Issue by pyhalov** [illumos/dev-guide#12]
One of the examples ( https://github.com/illumos/dev-guide/blob/master/workflow#L378 ) is incorrectly formatted on http://illumos.org/books/dev/workflow.html  - the code is concatenated in one line.

**Comment by rmustacc** [comment]
This is a bug in the markdown renderer that's been fixed in a newer version. Updating the bundled version fixes that.

**Comment by rmustacc** [comment]
This updates python-markdown2.py from 2.1.1 to 2.3.1.

**Comment by rmustacc** [comment]
Resolved in 9201b87.
