### ISSUE TITLE
cron guide update?

### ISSUE THREAD

**Issue by bdha** [illumos/dev-guide#20]
Automatically pull master and rebuild the guide.

@jclulow Any reason not to do this?

(@rzezeski asked if we could pull in some updates and you were traveling: https://github.com/illumos/dev-guide/pull/18#issuecomment-141711628)

I'm happy to do this work, unless there's a reason not to. Ryan would also be happy to spend the cycles on it.

- [x] Deploy key
- [x] Script
- [x] Chef + cron job

**Comment by bdha** [comment]
Takin' this.

**Comment by rmustacc** [comment]
Thanks @bdha!
