### ISSUE TITLE
Needs glossary

### ISSUE THREAD

**Issue by jblachly** [illumos/dev-guide#25]
I would like to add a glossary section; dev guide itself suggests I should check in before writing this myself. I would propose to make this an appendix, and place it before the documentation license section.

Please let me know thumbs up / thumbs down / thumbs sideways.

**Comment by rmustacc** [comment]
A glossary sounds great. Though I'd also say we should figure out where we're using terms that are confusing and excise them as well in addition to still having an appendix glossary.

**Comment by rmustacc** [comment]
Resolved in d91af5d.
