### ISSUE TITLE
CODEMGR_WS variable could be dynamic

### ISSUE THREAD

**Issue by sac** [illumos/dev-guide#32]
In the developer guide under section `Setting the path to our workspace` we explain setting
the CODEMGR_WS variable as: export CODEMGR_WS="/ws/rm/$GATE"

This could be made more dynamic by setting variable like:

export CODEMGR_WS="`git rev-parse --show-toplevel`"

@rmustacc Does this make sense? If so, I'll send a patch updating this.

**Comment by rmustacc** [comment]
@sac This is coming from the example environment files. It looks like the stock config file has been changed to match that which is different from when I had written this. Probably reasonable to update that.

**Comment by sac** [comment]
Ack!

**Comment by rmustacc** [comment]
I realized that might not have been clear, so please, feel free to send a patch.
