### ISSUE TITLE
Update glossary page about lint

### ISSUE THREAD

**Issue by domag02** [illumos/dev-guide#49]
The "[Appendix: Glossary of Terms](https://github.com/illumos/dev-guide/blob/master/glossary)" page not updated to the fact that we already eliminated
the Sun Studio lint dependency too ("_Sun Studio_" term).

We use the smatch static code analysis tool.

The phasing-out of lint started with this message from the illumos-developer mailing list:
[[HEADS-UP] GCC 7 shadow compiler; no more lint](https://illumos.topicbox.com/groups/developer/T6342764347f4dcef-Mf2b1afa24c9dd7fdb66f84f3).

There is an IPD (_illumos Project Discussion_) for this too: [IPD 2 Running smatch for Illumos builds](https://github.com/illumos/ipd/blob/master/ipd/0002/README.md).

Smatch introduced in Jan 5 2019 with this commit [10063 basic support for smatch](https://github.com/illumos/illumos-gate/commit/1f5207b7604fb44407eb4342aff613f7c4508508),
and from Jul 18 2019 this is the default tool, see this commit: [11462 enable smatch by default](https://github.com/illumos/illumos-gate/commit/7ae7577ce925f555e5e3410f14a3ccc896c842f2).

The "_Lint; linting_" term have to be updated too, to indicate that even if we don't use
the Sun Studio lint tool anymore, someone **might** use the "_linting_" term
interchangeably with "doing automated static code analysis" -- now with smatch.

**Comment by rmustacc** [comment]
Addressed in https://github.com/illumos/dev-guide/commit/d8fb9976b32a0c7e4e911c253e63e0a0eb14df07.
