### ISSUE TITLE
Instructions for creating a new build environment using `onu` missing  the `-d` flag

### ISSUE THREAD

**Issue by pilonsi** [illumos/dev-guide#51]
In the Testing section of the [Basic illumos Workflow](https://www.illumos.org/books/dev/workflow.html#testing) section, when it mentions using `onu` to create the new build environment the example command is missing the `-d` flag to point it to the locally built packages. Currently it is:

```
# onu -t new-nightly-be
#
```

When it should be:
```
# onu -t new-nightly-be -d /path/to/gate/packages/<arch>/nightly/
#
```

Missing the `-d` flag results in it trying to reach the ipkg.sfbay domain which no longer exists and it fails because it cannot resolve the hostname.

**Comment by rmustacc** [comment]
Resolved in [be1807c](https://github.com/illumos/dev-guide/commit/be1807cccc94c0e8881597bfdad9ee0c8e226f52).
