### ISSUE TITLE
Link to nightly(1) man page is broken

### ISSUE THREAD

**Issue by giorgio-v** [illumos/dev-guide#8]
`http://illumos.org/man/1/nightly`

**Comment by rzezeski** [comment]
I noticed the same issue with the `webrev(1)` link.

http://illumos.org/books/dev/workflow.html#webrev

I'm too many yaks deep to make a fix at the moment.

**Comment by rzezeski** [comment]
> Well, then there are two bugs here, one is that we should refer to 1onbld in the document. The other is that the manual pages for these tools improperly declare their sections, which is an illumos bug. So, until illumos changes the structure of those manual pages, we'll just have to update this to be something like nightly(1ONBLD).

Created illumos issue for the second bug.

https://www.illumos.org/issues/6205

**Comment by rzezeski** [comment]
Once 6205 is in this script needs updating too:

https://github.com/jclulow/illumos-webman/blob/master/tools/make_mandir.sh#L39
